sudo: required

language: generic

services:
  - docker

before_install:
  - docker-compose build phantomjs-tests

script:
  - docker-compose run --rm phantomjs-tests
  - docker-compose run --rm phantomjs-tests ./node_modules/eslint/bin/eslint.js .
